# RBS Pools Schema for running buffer service performance test.
---
poolConfigs:
  - poolId: "resource_perf_v1"
    size: 1500
    resourceConfigName: "resource_perf_v1"
  - poolId: "resource_perf_v2"
    size: 1500
    resourceConfigName: "resource_perf_v2"
