# RBS Pools Schema for running buffer service performance test.
---
poolConfigs:
  - poolId: "workspace_manager_v3"
    size: 20
    resourceConfigName: "workspace_manager_v3"
  - poolId: "workspace_manager_v4"
    size: 20
    resourceConfigName: "workspace_manager_v4"
  - poolId: "workspace_manager_v5"
    size: 20
    resourceConfigName: "workspace_manager_v5"
  - poolId: "cwb_ws_perf_v1"
    size: 500
    resourceConfigName: "cwb_ws_perf_v1"
  - poolId: "vpc_sc_v1"
    size: 500
    resourceConfigName: "vpc_sc_v1"
