openapi: 3.0.0
info:
  title: Terra Resource Buffer Service Resource Config
  description: |
    Terra Resource Buffering Service definitions of resource config schema.
    The templates follows Cloud original openApi, schemas can be found here: https://github.com/APIs-guru/openapi-directory/tree/master/APIs
  version: 0.0.1

# This file defines component models to be reused, not a service path.
paths: {}

components:
  schemas:
    # We are not doing polymorphism at this moment because of lack of support in swagger-codegen or openApiGenerator
    # Now ResourceConfig contains all possible resource configs, and we will assume there is only one being set
    # when using this.
    ResourceConfig:
      description: |-
        Reource Config template in Terra
      required:
        - configName
      properties:
        configName:
          description: |-
            Name of the config
          type: string
        gcpProjectConfig:
          $ref: '#/components/schemas/GcpProjectConfig'
      type: object

    GcpProjectConfig:
      description: |-
        Represents a GCP Project resource with extra cloud resource setup when creating project.
      required:
        - projectIdPrefix
      properties:
        projectIDGenerator:
          $ref: '#/components/schemas/ProjectIDGenerator'
        parentFolderId:
          description: |-
            The parent folder id of created project.
          type: string
        billingAccount:
          description: |-
            The billing account id the project associated to.
          type: string
        enabledApis:
          description: |-
            List of APIs to enable
          type: array
          items:
            type: string
        iamBindings:
          description: |-
            List of GCP IAM bindings
          type: array
          items:
            $ref: '#/components/schemas/IamBinding'
        network:
          $ref: '#/components/schemas/Network'
      type: object

    ProjectIDGenerator:
      description: |-
        How to generate project ID, including prefix and the nameing schema. For example, projectIDPrefix is
        aou_rw, projectIDScheme is random_char, the generated project ID might be aou_rw_a1bc23
      properties:
        projectIDPrefix:
          description: |-
            The created project name prefix.
          type: string
        projectIDScheme:
          type: string
          # swagger-codegen always looks for and removes a common prefix for
          # enum values, which breaks enums that only have a single value.
          # PLACEHOLDER_VALUE should be removed when we have an actual second value
          # to use.
          # TODO(PF-228): Add naming scheme for GCP style(TWO_WORDS_NUMBER)
          enum: ['PLACEHOLDER_VALUE', 'RANDOM_CHAR']
          description: >
            ID Scheme:
             * `RANDOM_CHAR` - all random letters/numbers, length is defined in generator code. This is also the default scheme.
      type: object

    IamBinding:
      description: Associates `members` with a `role`.
      properties:
        members:
          description: "GCP identities, see https://cloud.google.com/resource-manager/reference/rest/Shared.Types/Binding"
          items:
            type: string
          type: array
          example: ["group:foo-group@googlegroup.com", "serviceAccount:bar-sa@test.iam.gserviceaccount.com"]
        role:
          description: Role that is assigned to `members`. For example, `roles/viewer`, `roles/editor`, or `roles/owner`.
          type: string
      type: object

    Network:
      description: Network setup for the project.
      properties:
        enableNetworkMonitoring:
          description: |-
            Make network traffic is measured. If enabled, turn on flow logs, enable private google access.
            See https://docs.google.com/document/d/1ccz2kzDL68CPofZ-b95ykQIudCgh7OCSFJ4Ym4Oz0r0/edit for more context.
          type: boolean
      type: object
