rbs:
  db:
    password:
    recreate-db-on-start: false
    update-db-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${RBS_DATABASE_NAME}
    username:
  server:
    port: 8080
  stairway:
    db:
      password:
      uri: jdbc:postgresql://127.0.0.1:5432/${RBS_STAIRWAY_DB_NAME}
      username:
    force-clean-start: false
    max-parallel-flights: 40
    migrate-upgrade: true
    quiet-down-timeout: 20s
    terminate-timeout: 5s
