rbs:
  db:
    password:
    recreate-db-on-start: false
    update-db-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${RBS_DATABASE_NAME}
    username:
  primary:
    scheduler-enabled: true
  pool:
    # The Folder to have all RBS configs.
    # TODO: Investigate where and how to put those files.
    config-path:
    # Whether to update pool when config changes during server startup.
    # Might be useful to avoid potential backward compatibility casued by config change and make tests easier.
    update-pool-on-start: true
  stairway:
    db:
      password:
      uri: jdbc:postgresql://127.0.0.1:5432/${RBS_STAIRWAY_DATABASE_NAME}
      username:
    force-clean-start: false
    max-parallel-flights: 40
    migrate-upgrade: true
    quiet-down-timeout: 20s
    terminate-timeout: 5s

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application:
    name: rbs
  resources:
    cache.cachecontrol:
      max-age: 0
      must-revalidate: true
    static-locations: classpath:/api/
