rbs:
  crl:
    # If CRL is used in testing mode.
    testing-mode: true
    # Janitor configs used in test.
    janitor-client-credential-file-path:
    janitor-track-resource-project-id:
    janitor-track-resource-topic-id:

  db:
    password:
    recreate-db-on-start: false
    update-db-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${RBS_DATABASE_NAME}
    username:
  primary:
    scheduler-enabled: true
  pool:
    # The Folder to have all RBS configs.
    # TODO: Investigate where and how to put those files.
    configPath: config/dev
    # Whether to update pool when config changes during server startup.
    # Might be useful to avoid potential backward compatibility casued by config change and make tests easier.
    update-pool-on-start: true
  server:
    port: 8080
  stairway:
    db:
      password:
      uri: jdbc:postgresql://127.0.0.1:5432/${RBS_STAIRWAY_DATABASE_NAME}
      username:
    force-clean-start: false
    max-parallel-flights: 40
    migrate-upgrade: true
    quiet-down-timeout: 20s
    terminate-timeout: 5s
