rbs:
  db:
    password: ${DATABASE_USER_PASSWORD}
    recreate-db-on-start: false
    update-db-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
  server:
    port: 8080
  pool:
    update-pool-on-start: true
    # The Folder to have all RBS configs.
    # TODO: Investigate where and how to put those files.
    configPath: config/dev