# RBS Pools Schema in tools environment
---
poolConfigs:
  - poolId: "cwb_ws_fiab_v1"
    size: 100
    resourceConfigName: "cwb_ws_resource_fiab_v1"
  - poolId: "workspace_manager_v1"
    size: 100
    resourceConfigName: "workspace_manager_v1"
  - poolId: "cwb_ws_fiab_v2"
    size: 100
    resourceConfigName: "cwb_ws_resource_fiab_v2"
  - poolId: "workspace_manager_v2"
    size: 100
    resourceConfigName: "workspace_manager_v2"
  - poolId: "workspace_manager_v3"
    size: 100
    resourceConfigName: "workspace_manager_v3"
  - poolId: "workspace_manager_v4"
    size: 100
    resourceConfigName: "workspace_manager_v4"
  - poolId: "workspace_manager_v6"
    size: 100
    resourceConfigName: "workspace_manager_v6"
