# All Of Us buffered workspace template
---
configName: "aou_ws_resource_stable_v1"
gcpProjectConfig:
  projectIdSchema:
    prefix: "aou-rw-stable"
    scheme: "RANDOM_CHAR"
  # firecloud.org/terra_dev_aou_stable
  parentFolderId: "96867205717"
  billingAccount: "0106B0-41CAA9-427C96"
  enabledApis:
  - "bigquery-json.googleapis.com"
  - "compute.googleapis.com"
  - "container.googleapis.com"
  - "cloudbilling.googleapis.com"
  - "clouderrorreporting.googleapis.com"
  - "cloudkms.googleapis.com"
  - "cloudtrace.googleapis.com"
  - "containerregistry.googleapis.com"
  - "dataflow.googleapis.com"
  - "dataproc.googleapis.com"
  - "dns.googleapis.com"
  - "genomics.googleapis.com"
  - "logging.googleapis.com"
  - "monitoring.googleapis.com"
  - "notebooks.googleapis.com"
  - "storage-api.googleapis.com"
  - "storage-component.googleapis.com"
  network:
    enableNetworkMonitoring: "true"
