# Data Repo buffered workspace template
---
configName: "datarepo_v1"
gcpProjectConfig:
  projectIdSchema:
    prefix: "datarepo-prod"
    scheme: "RANDOM_CHAR"
  parentFolderId: "815384374864" # firecloud.org/terra-datarepo
  billingAccount: "00708C-45D19D-27AAFA"
  enabledApis:
    - "bigquery-json.googleapis.com"
    - "firestore.googleapis.com"
    - "firebaserules.googleapis.com"
    - "storage-component.googleapis.com"
    - "storage-api.googleapis.com"
    - "cloudbilling.googleapis.com"
    - "appengine.googleapis.com"
    - "compute.googleapis.com"
  network:
    enableNetworkMonitoring: "false"
