# Resource Buffer Service Pools Schema in alpha environment
---
poolConfigs:
- poolId: "cwb_ws_alpha_v1"
  size: 100
  resourceConfigName: "cwb_ws_resource_alpha_v1"
- poolId: "datarepo_v1"
  size: 300
  resourceConfigName: "datarepo_v1"